### ISSUE TITLE
How to add 1 inch support 

### ISSUE THREAD

**Issue by mkroxm** [Haehnchen/uniswap-arbitrage-flash-swap#8]
i have just updated factory and router in address
{
            router: "0x11111112542D85B3EF69AE05771c2dCCff4fAa26",
            factory: "0xD41B24bbA51fAc0E4827b6F94C0D6DDeB183cD64"
        },
in the file 
 file but getting this error 
error Error: Returned error: execution reverted
    at Object.ErrorResponse (C:\bsc\node_modules\web3-core-helpers\lib\errors.js:28:19)
    at Object.callback (C:\bsc\node_modules\web3-core-requestmanager\lib\index.js:303:36)
    at C:\bsc\node_modules\web3-providers-ws\lib\index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (C:\bsc\node_modules\web3-providers-ws\lib\index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\bsc\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onMessage (C:\bsc\node_modules\websocket\lib\W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (C:\bsc\node_modules\websocket\lib\W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:376:20)
    at WebSocketConnection.processFrame (C:\bsc\node_modules\websocket\lib\WebSocketConnection.js:554:26)
    at C:\bsc\node_modules\websocket\lib\WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  data: null
}
^C

Please help me Out thanks in advance !!!

**Comment by mindfulme** [comment]
are you trying to use all available dexs from 1inch for arbitrage?

**Comment by mindfulme** [comment]
@mkroxm any progress?

**Comment by Haehnchen** [comment]
The repo is already saying it "**Uniswap**  Flash Swap Contract". 1inch is not a uniswap fork. 

but you can check their supported dexs platforms, most of them are uniswap forks and work just extra eg. the router and factory adress from the api.
